-- Your SQL goes here
--CREATE TABLE IF NOT EXISTS species (
-- 	species varchar(256) NOT NULL PRIMARY KEY
-- );
-- 
-- INSERT INTO species values('Cat'),('Dog'),('Bird'),('Fish');
-- 
-- CREATE TABLE IF NOT EXISTS species_variety (
-- 	species varchar(256) REFERENCES species,
-- 	variety varchar(256),
-- 	PRIMARY KEY (species, variety)
-- );
-- 
-- INSERT INTO species_variety values ('Cat','Unknown'),
-- 	('Cat', 'US short'),
-- 	('Dog', 'Unknown'),
-- 	('Dog', 'Chi wawa');

CREATE TABLE IF NOT EXISTS pets (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	,name varchar(64) NOT NULL
	,species varchar(256) NOT NULL
	,variety varchar(256) NOT NULL
	,birthday date NULL
	,description text NULL
--  FOREIGN KEY (species, variety) REFERENCES species_variety (species, variety)
);

